### PR TITLE
Added two more practical talks/presentations

### PR DESCRIPTION
**Pull request by sumanp**
I want to contribute to this list and help the maintainers, so:

- [x] I've accepted the terms of the `CC0` License;
- [x] I've added the topic `rubyml` to the contributed repository if appropriate.

### CODE REVIEW

**Comment by arbox** [comment]
Hi @sumanp ,

thank you for these suggestions!

I'd ask you to do the following changes to your PR:
- add one thing per commit;
- add the Github mention of the author name to the commit message if possible;
- add new stuff to the bottom of the appropriate categories.

Thank you again and try to refine your PR :+1:

**Comment by sumanp** [comment]
Hi @arbox,

Thank you for the tip & the encouragement.
I'll certainly follow the guidelines for the PR.

Thanks 👍

**Comment by arbox** [comment]
Apropos, you don't have to close the PR, you can just push to the same branch again, the PR will be automatically updated :smiley:

**Comment by sumanp** [comment]
Aah! that's so convenient. My first contribution you see. 
Thank you for all the suggestion 😄

**Comment by arbox** [comment]
You're welcome!

**Comment by arbox** [comment]
Thank you! Added :smiley:

**Pull request merged**
