### PR TITLE
Gradient boosting

### PR DESCRIPTION
**Pull request by ankane**
Hey @arbox, I recently released two gems for gradient boosting, and along with the xgboost gem, thought it'd make sense to create a new category for it. Let me know your thoughts.

### CODE REVIEW

**Comment by arbox** [comment]
Hey @ankane, glad to see you on this list (I'm heavy user of your pghero).
Sure, new category is justified. And the structure will evolve over the time.

**Comment by ankane** [comment]
Thanks @arbox, that's great to hear :) Looks like I forgot to add the category to the table of contents. I can submit another PR if you want, or feel free to just add it.

**Comment by arbox** [comment]
@ankane 
I'll do it myself, no worries :)

**Comment by ankane** [comment]
Awesome, thanks 👍

**Pull request merged**
