### PR TITLE
Add Matthew Kirk to presentations

### PR DESCRIPTION
**Pull request by hexgnu**
Hey @arbox thanks for putting this together.

Back between 2012 and 2014 I did quite a few presentations on machine learning with ruby and feel like I should be added to this as well.

Feel free to watch them, they were all done by confreaks and went over fairly well. There's some presentations that are doubled up that I decided not to attach (like my presentation at rubyconf).

thanks!

### CODE REVIEW

**Comment by arbox** [comment]
Hey Matt,
thank you! Nice sources! If you know more please contribute :)

Two ponts:
1. if possible add the slides to those videos in superscripts as you did with the recordings;
2.  could you please squash all commits into only one?

Thank you again!

**Comment by hexgnu** [comment]
I don't think I have the slides anymore... I just cleaned off my mac :-/

I'll squash the commits.

**Comment by hexgnu** [comment]
K squashed the commits. Thanks @arbox

**Comment by arbox** [comment]
Thank you! Merged :)

**Pull request merged**
